#!/usr/bin/expect -f

set timeout 20
set host "72.61.229.171"
set user "root"
set password ")vbofQi/lHXSMqF?Nk8E"

spawn ssh -o StrictHostKeyChecking=no $user@$host

expect "password:"
send "$password\r"

expect "#"
send "tail -n 50 /var/log/nginx/error.log\r"

expect "#"
send "cat /etc/nginx/sites-enabled/nplusone\r"

expect "#"
send "ls -ld /var/www/nplusone/.next/static\r"

expect "#"
send "exit\r"

expect eof
