#!/usr/bin/expect -f

set timeout 20
set host "72.61.229.171"
set user "root"
set password ")vbofQi/lHXSMqF?Nk8E"

spawn ssh -o StrictHostKeyChecking=no $user@$host

expect "password:"
send "$password\r"

expect "#"
send "cat /etc/nginx/sites-enabled/ibaadattracker.in\r"

expect "#"
send "cat /etc/nginx/sites-enabled/nplusonefashion.com\r"

expect "#"
send "cat /etc/nginx/sites-enabled/texna-react\r"

expect "#"
send "exit\r"

expect eof
