#!/usr/bin/expect -f

set timeout 20
set host "72.61.229.171"
set user "root"
set password ")vbofQi/lHXSMqF?Nk8E"

# Read local .env.local content (passed as argument or read from file?)
# Expect scripts are hard to pass multiline strings to.
# Better to use scp.

spawn scp -o StrictHostKeyChecking=no .env.local $user@$host:/var/www/nplusone/.env

expect {
  "password:" {
    send "$password\r"
    exp_continue
  }
  eof
}
